name: Build

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget llvm-dev llvm-runtime llvm clang build-essential cmake libfmt-dev
          curl -fsSL https://xmake.io/shget.text | bash

      - name: Build
        run: |
          xmake build blang
          xmake install -o out blang
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: blang-linux
          path: out/bin/blang

  windows-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-clang mingw-w64-ucrt-x86_64-llvm bison mingw-w64-ucrt-x86_64-xmake mingw-w64-ucrt-x86_64-fmt git
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: msys2 {0}
        run: |
          xmake build blang
          xmake install -o out

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: blang-windows
          path: out/bin/blang.exe
