name: Windows Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install tools via Chocolatey
        run: |
          choco install winflexbison -y
          choco install llvm -y

      - name: Configure PATH
        run: |
          echo "C:\Program Files\LLVM\bin" >> $env:GITHUB_PATH
          echo "C:\ProgramData\chocolatey\lib\winflexbison\tools" >> $env:GITHUB_PATH

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF
          cmake --build build --config Debug
          mv build/blang.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blang-artifact
          path: blang.exe
