name: Windows Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-x86_64-gcc clang llvm bison xmake fmt
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: msys2 {0}
        run: |
          xmake build
