name: Windows Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-clang mingw-w64-ucrt-x86_64-llvm bison mingw-w64-ucrt-x86_64-xmake mingw-w64-ucrt-x86_64-fmt git
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: msys2 {0}
        run: |
          xmake build
          xmake install -o out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blang-artifact
          path: out/bin/blang
